### ISSUE TITLE
ImportError: pyutilib.enum has been removed.

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#125]
Somehow, installing windnode-abw on the SRVSIM01 leads to an import error. Traceback

```
Traceback (most recent call last):
  File "run_scenario.py", line 11, in <module>
    from windnode_abw.model import Region
  File "/home/local/RL-INSTITUT/guido.plessmann/git-repos/WindNODE_ABW/windnode_abw/model/__init__.py", line 10, in <module>
    from windnode_abw.model.region.tools import \
  File "/home/local/RL-INSTITUT/guido.plessmann/git-repos/WindNODE_ABW/windnode_abw/model/region/tools.py", line 10, in <module>
    import oemof.solph as solph
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/oemof/solph/__init__.py", line 1, in <module>
    from oemof.solph.network import (Sink, Source, Transformer, Bus, Flow,
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/oemof/solph/network.py", line 20, in <module>
    from oemof.solph import blocks
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/oemof/solph/blocks.py", line 13, in <module>
    from pyomo.core import (Var, Set, Constraint, BuildAction, Expression,
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyomo/core/__init__.py", line 11, in <module>
    from pyomo.core.expr import *
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyomo/core/expr/__init__.py", line 36, in <module>
    from .calculus.derivatives import differentiate
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in <module>
    from pyutilib.enum import Enum
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/windnode_abw/lib/python3.8/site-packages/pyutilib/enum/__init__.py", line 14, in <module>
    raise ImportError("""pyutilib.enum has been removed.
ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.
```

Does this sound familiar to you?

**Comment by nesnoj** [comment]
hmmm first I thought this might be related to the oemof 0.4 which is incompatible to our model but that's not the case as the package has been renamed.
I just tested and install works out like a charm:
```bash
virtualenv --python=python3.6 windnode_abw_test/
source windnode_abw_test/bin/activate
pip3 install -e ~/git-repos/WindNODE_ABW/
```

**Comment by gplssm** [comment]
Thanks for the quick reply!

With

```
conda create -n windnode_abw python=3.6
conda activate windnode_abw
pip install -e .
python run_scenario.py
```

even with 

```
pip install --no-cache-dir -e .
```

I get the above error message.

Same is true when using the proposed installation using virtualenv :cry: 

The error is caused by the import statement

```
from pyutilib.enum import Enum
```

which can be easily reproduced by

```
python -c "from pyutilib.enum import Enum"
```

Running this using the environment on my laptop does not lead to this error :thinking: 

Hence, I tried to reproduce my local environment on the server with

```
pip freeze > windnode_abw_requirements_nb-49.txt
pip install -r windnode_abw_requirements_nb-49.txt
```
using conda works out :tada: 
For reference, the requirements file is [here](https://gist.github.com/35b8b7e6e2cc4a6315cc25a68d8b08ae).

It works, but the solution isn't really satisfying on the long run...

**Comment by nesnoj** [comment]
Ok, but were u able to bring it down to a very package/python version mismatch or something?

**Comment by gplssm** [comment]
> Ok, but were u able to bring it down to a very package/python version mismatch or something?

Nope, therefore I decided to add a "wontfix" label

**Comment by nesnoj** [comment]
I love that magic stuff.. :alien:

**Comment by gplssm** [comment]
Used an ugly work-around:

`pip install "pyomo>=5.7"`

Since pyomo is introduced by oemof-solph, it might make sense to upgrade to oemof-solph v0.4.1. But I'm certainly sure, it would require to partially re-work oemof-solph related code.

**Comment by nesnoj** [comment]
> Hence, I tried to reproduce my local environment on the server with
> 
> ```
> pip freeze > windnode_abw_requirements_nb-49.txt
> pip install -r windnode_abw_requirements_nb-49.txt
> ```

Had the same issue on pc50, this fix worked (used reqs list from srv) also with venv (not conda) ..thx!

**Comment by nailend** [comment]
> pip freeze > windnode_abw_requirements_nb-49.txt
> pip install -r windnode_abw_requirements_nb-49.txt

worked for me as well!

> Used an ugly work-around:
> 
> `pip install "pyomo>=5.7"`
> 
> Since pyomo is introduced by oemof-solph, it might make sense to upgrade to oemof-solph v0.4.1. But I'm certainly sure, it would require to partially re-work oemof-solph related code.

did not work properly as it ended up in new errors!
