### ISSUE TITLE
KeyError: 'pv_land_use_scenario'

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#23]
When I run `run_analysis.py` on scenario "NEP2035" I get the following traceback

```
14:12:01-INFO: Importing RE potential areas...
Traceback (most recent call last):
  File "/home/guido/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/guido/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/guido/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/guido/pycharm-community-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/guido/git/WindNODE_ABW/windnode_abw/run_analysis_local.py", line 27, in <module>
    region = Region.import_data(cfg)
  File "/home/guido/git/WindNODE_ABW/windnode_abw/model/__init__.py", line 404, in import_data
    region = cls(**{**import_db_data(cfg), 'cfg': cfg})
  File "/home/guido/git/WindNODE_ABW/windnode_abw/model/__init__.py", line 87, in __init__
    self._muns.update(calc_available_pv_capacity(self))
  File "/home/guido/git/WindNODE_ABW/windnode_abw/model/region/tools.py", line 829, in calc_available_pv_capacity
    if region.pot_areas_pv_scn is None:
  File "/home/guido/git/WindNODE_ABW/windnode_abw/model/__init__.py", line 344, in pot_areas_pv_scn
    if self._cfg['scn_data']['generation']['re_potentials'][
KeyError: 'pv_land_use_scenario'
```

**Comment by nesnoj** [comment]
You're probably trying to analyze results generated with an outdated version. The scn config is read from `~/.windnode_abw/results/<TIMESTAMP>/NEP2035/meta.json` which does not contain the parameter 'pv_land_use_scenario' yet.
Hence, the new functions and methods, in this case `pot_areas_pv_scn()` won't work.
Simply do a run with the new version and use those results.

**Comment by nesnoj** [comment]
New nice to have issue to tackle this problem: #24

**Comment by gplssm** [comment]
Thanks! That was the problem...
